version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: keyraccoon_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keyraccoon
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: keyraccoon_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: keyraccoon_app
    environment:
      SERVER_PORT: 3000
      SERVER_HOST: 0.0.0.0
      ENVIRONMENT: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: keyraccoon
      DB_SSLMODE: disable
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASS:
      REDIS_DB: 0
      JWT_SECRET: <JWT_SECRET>
      JWT_EXPIRE: 60
      ADMIN_EMAIL: admin@keyraccoon.com
      ADMIN_PASSWORD: AdminPassword123
      CORS_ORIGIN: "*"
    ports:
      - "10.8.0.1:3245:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/health",
        ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
